### ISSUE TITLE
Add Contributor page to website

### ISSUE THREAD

**Issue by marissap** [legesher/legesher-dot-io#23]
What about creating another page like _dreamteam.html_ and linking it in the footer. Then every time someone contributes they can make a pull request adding their name to that html page?

We could add that requirement to contributing.md.

<img width="1183" alt="Screen Shot 2019-10-05 at 1 00 24 AM" src="https://user-images.githubusercontent.com/20907831/66250080-927f8d00-e70b-11e9-9a07-f5cb9e57b15c.png">

_Originally posted by @marissap in https://github.com/legesher/legesher-dot-io/issues/17#issuecomment-538616822_

**Comment by madiedgar** [comment]
I love it! it would be a really cool way to recognize our contributors 😄 

Somethings to note: 
- I would love to include every contributors across the entire project (not just the website repo) since all the repos play well with each other ❤️. Your idea to add it as a requirement in the `contributing.md` in each of the repositories is probably the best place to start 👌 
- I've been meaning to add [`allcontributors`](https://allcontributors.org/) to the projects' config / readme, so I'll be sure to get that done soon for you. I'd love to highlight the types of contributors we have on our project as well! Anyway you can incorporate that into the design of the page would be amazing 👍

**Comment by madiedgar** [comment]
Closing this issue as it was resolved in #25
